[package]
name = "gitstars"
version = "0.1.0"
edition = "2024"

[dependencies]
bon = "3.6.3"
gitlab = "0.1711.0"
octocrab = "0.44.1"
serde = "1.0.219"
thiserror = "2.0.12"
tokio = {version = "1.45.0", features = ["full"]}
